### ISSUE TITLE
Pressing enter twice rapidly causes a message to be sent twice.

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#101]
Ironically this is also the only place in our codebase where we use javascript, We should probably investigate further if we can handle resizing of the textarea within rust / dioxus itself maybe there are better docs on the Tao side.

**Comment by phillsatellite** [comment]
I wanted to add on that I also noticed this happens when user does shift+enter to tab down a line, it will send the message 

https://user-images.githubusercontent.com/93608357/194903123-95490d8b-5f82-414b-b49f-eb3ce41638fc.mov

**Comment by dariusc93** [comment]
@phillsatellite Thats likely because its still detects the enter key being pressed.

**Comment by dariusc93** [comment]
To extend on this, if you press enter anytime after sending a message without typing anything else, it would send the same message, This tells me that something is still retaining the text field after it is cleared out.

**Comment by InfamousVague** [comment]
This is almost certainly because the text is being cleared in JS not in
dioxus. When I was first building I couldn't find a reliable way to clear a
text area since it reacts different to a input. It would be worthwhile
spending some time on the chat bar to make it reusable and support the
current functionality without the use of Javascript. To add more reason not
every deployment of Uplink will support JS so we should try to avoid usage
in compiled code.

**Comment by dariusc93** [comment]
Resolved in #126
