### ISSUE TITLE
cmd-v keyboard input issues on Mac

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/WarpGUI#11]
On Mac only release you can't use Cmd-V to paste in a friend code, you  have to right click and do paste. On Windows Ctrl-V works fine. 

Dev Notes:
One suggestion is to build one of dioxus sample apps that utilizes the text fields and see if the issue is there. May want to use a older commit that is based on the version we are using before trying what is on main branch.

**Comment by InfamousVague** [comment]
@dariusc93 can you take a first pass at this? I've looked around quite a bit but couldn't find anything substantial.

**Comment by InfamousVague** [comment]
I put in a fix on dev.

**Comment by InfamousVague** [comment]
Sorry for the QA team for pushing straight to dev

**Comment by dariusc93** [comment]
Been confirmed to be working from the changes made but will leaving this opened for the weekend for extended testing.

**Comment by stavares843** [comment]
🔨

**Comment by InfamousVague** [comment]
> 🔨

🪓
