### ISSUE TITLE
When User sends friend request, it will be duplicated on senders side 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#115]
**Device** Macbook Pro M1

**Issue:** When User A sends a friend request to User B, and they go to _Outgoing Requests_ there will be 2 sent friend request one of them is the request you sent to User B and the other will just forever load 

User B was still able to accept friend request and start chat fine

**Screenshot:**

This was the senders side 

<img width="342" alt="Captura_de_ecra_2022-10-11_as_18 26 48" src="https://user-images.githubusercontent.com/93608357/195161693-44db4a26-c31a-4b62-8c80-ea2fb5ce8a57.png">

**Comment by dariusc93** [comment]
Does it still show after reloading the app @phillsatellite ?

**Comment by phillsatellite** [comment]
@dariusc93 @stavares843 had the duplicate friend request appear on her side, I'm 99% sure after refreshing it was still there but she can verify for sure

**Comment by dariusc93** [comment]
I only ask because im unable to reproduce this on dev branch or the branch I been working on. Is the latest commit being used and did you make sure to do `cargo update` to make sure git dependencies are updated too?

**Comment by phillsatellite** [comment]
Havent been able to replicate after testing, going to move ticket to closed for now
