### ISSUE TITLE
Typing indicator - Minor glitch when sending messages 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#117]
**Devices:** Macbook Pro M1

**Issue:** It seemed like when the user sends a message the typing indicator looks a little glitchy 

**How to replicate:**
1. Send messages in chat

**Screen recording:**

https://user-images.githubusercontent.com/93608357/195164779-062ff3f4-8513-4c15-9f5d-e2f3a2d6f13d.mov

**Comment by phillsatellite** [comment]
Verified I could still replicate on Dev branch with most latest changes

**Comment by sdwoodbury** [comment]
I believe that https://github.com/Satellite-im/Uplink-Desktop/pull/200/files introduced this bug by switching from a textarea to an editable div.

**Comment by dariusc93** [comment]
@phillsatellite are you able to reproduce this?

**Comment by phillsatellite** [comment]
@dariusc93 Wasnt able to closed issue 👍
