### ISSUE TITLE
friend request behavior is inconsistent 

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/WarpGUI#12]
Seems like it only works about half the time or less. Need to figure out what we are missing here.

**Comment by InfamousVague** [comment]
Could we meet on Monday to discuss converting this to a "add sync node support for warp and get sync nodes setup" ticket? Would be nice for "Milestone 1"

**Comment by InfamousVague** [comment]
I think this can be closed for now; we will need sync nodes to further add stability IMHO.
