### ISSUE TITLE
Navbar position is incorrect

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#122]
After recent changes to dev, the navbar is not in the correct position 

![image](https://user-images.githubusercontent.com/3918024/195765859-548a8feb-18c3-4c52-80d0-db23668ef5f5.png)

cc @InfamousVague @jasonwoodland 

EDIT: This seem to happen when there is no active chat. Once a conversation is created, it will go back to its correct position

**Comment by lgmarchi** [comment]
This problem was solved. closing the issue.
![image](https://user-images.githubusercontent.com/63157656/201184683-fdb585f8-1f58-4451-9f28-9d7973d3018d.png)
