### ISSUE TITLE
feat: add button to minimize friends window

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/WarpGUI#124]
proposed change drawn in red

![friend-window-edited](https://user-images.githubusercontent.com/8636602/196508742-815779ca-3ceb-4159-b79a-0a31850cfd8f.png)

Currently if the user clicks the 'friends' button, this window appears and the user must click outside the window to close it. I think it would be beneficial to add a button to close this window.

**Comment by lgmarchi** [comment]
No bottom sheet now. Closing Issue.
![image](https://user-images.githubusercontent.com/63157656/201185152-cdee68da-b911-4903-9679-eb4fc1ee446f.png)
