### ISSUE TITLE
Windows: keyboard input issues for windows builds

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/WarpGUI#13]
app just seems broken but really there is something wrong with keyboard inputs right?

**Comment by InfamousVague** [comment]
@tooshel is this safe to close?

**Comment by tooshel** [comment]
@InfamousVague On your new branch I was having issues with the keyboard on windows again so we should probably keep it open.

**Comment by InfamousVague** [comment]
@tooshel can you check tomorrow if it's still the case on dev?

**Comment by tooshel** [comment]
@InfamousVague YES! This is fixed now! I tried on Windows and Mac and I could click on the canvas and still could type in my passcode. Nicely done!
