### ISSUE TITLE
UI freezes after maximizing 

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#133]
When the application is maximized and you use the profile popup and change the size of the window, the UI will freeze. Any other time it will continue to operate as normal.

**Comment by phillsatellite** [comment]
@dariusc93 Are you still able to replicate this? I was trying this morning but haven't been able to yet

**Comment by lgmarchi** [comment]
@phillsatellite and @dariusc93 I am not able to replicate. Closing this Issue.
