### ISSUE TITLE
MultiPassExtensionUnavailable when pin > 4 numbers

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/WarpGUI#135]
If the pin is longer than 4 characters, MultiPassExtensionUnavailable is triggered.

You can see this error if you change the error in `_account_fetch_status` to 
```        Err(e) => {
            println!("Error: {e}");
            use_router(&cx).push_route("/auth", None, None);
            true
        }
``` 
(thank you @dariusc93 for debugging)

In `src/components/prelude/unlock/mod.rs`
![image](https://user-images.githubusercontent.com/2993032/197316529-beccf5e0-fd2d-49f1-a6f5-3e83c60eeb17.png)

tries to unlock at 4 chars no matter what, if you change this to 6 it will work on enter or at the current max.

We may want to put the min and max in the config, waiting on guidance from @InfamousVague

**Comment by dariusc93** [comment]
After investigating this morning and small changes to improve on this in warp so it should work fine now. Leaving this open for @WanderingHogan to confirm.

**Comment by WanderingHogan** [comment]
@dariusc93 confirmed you fixed the issue
