### ISSUE TITLE
Stop popup from rerendering

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#140]
In #36 I made a note of the popup component was being rerendered when its being displayed. This is likely due to the animation being done and it checking to see if it can show or hide the component which a fix never made it into #102. This should be looked into so it wouldnt be rerendered when its being displayed.

**Comment by sdwoodbury** [comment]
An alternative for this may be to stop using the `Popup` element. It will be removed from the `Friends` element regardless. After that, it will only be used by the `Profile` element (within `Settings`). It should be easy enough to make a route for `Profile`.

**Comment by sdwoodbury** [comment]
I did some investigating by adding `printf` statements in the code. with commit `c3121eb47efda17f2b3fb2fc21e77dd3670f796c` it's clear that the `Popup` component is getting constantly re-rendered. There are additional re-renders of the `IconInput` and it's parent, but not nearly as much as the `Popup`

Later on the Friends component is moved to its own route. with commit `c3bb579a199d085e68fe0eb4b00851df2c7ee7c9`, the `FindFriends` and `IconInput` elements are being constantly re-rendered, though not as fast as the `Popup`. element was 

This is nuts. all the state changes which I would expect to cause a re-render happen on inputs and button presses, but the re-render occurs on its own. 

Changes that I would have expected to help can be viewed in branch `fix/140-3`
