### ISSUE TITLE
UI fixes required for multiline support on inputs

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#142]
There are slight Ui issues with the inputs that need fixing. 

* When you first start typing in the input it changes size slightly even when we don't need to.
* Input padding is off and text is not properly aligned to the center.
* resizable inputs should not have the resize handle.

![Image](https://user-images.githubusercontent.com/1770198/198835342-4ff81a26-7db5-4322-9dab-8fa76287c218.png)

![Image](https://user-images.githubusercontent.com/1770198/198835353-9eef88cd-6c1c-4590-b046-7b16b0665e5b.png)

**Comment by jasonwoodland** [comment]
@InfamousVague on which platform is this occurring? Seems ok on macOS

**Comment by josephmcg** [comment]
same, can't recreate this

**Comment by InfamousVague** [comment]
I removed the multiline support for now because it was causing a bunch of issues; I think there are two options one of which is more work but is more suitable long term, the other would be easier (i think) but good for the short term. 

One is to create a div which displays the content inside the textarea and has the multiline support inside there which will allow us to get multi-line "auto grow" support as well as do inline styling for things like markdown, etc.

The other would be if we can find a CSS way to allow the textarea to grow by itself as we get more lines.

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/Uplink-Desktop/pull/200

**Comment by InfamousVague** [comment]
Needs a few more things, hoping the team can help my nooby self with.

**Comment by iltumio** [comment]
this ticket should be already closed since the PR has been merged in

**Comment by lgmarchi** [comment]
Closing Issue. PR already merged.
