### ISSUE TITLE
UI Issue with expanding popup

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#147]
When expanding the popup component, it would cause the background to render in a weird way. 

![image](https://user-images.githubusercontent.com/3918024/198883689-9f6251bc-bf6e-49d1-bf09-09aa2d108683.png)

**Comment by InfamousVague** [comment]
This is an issue only with Linux @dariusc93, I don't think we can fix this, they need to fix how the `backdrop-filter` renders in linux.
