### ISSUE TITLE
Online Indicator Oddities

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#149]
The status indicators don't quite match up correctly. See screenshot.

![Image](https://user-images.githubusercontent.com/1770198/198952771-d179b8ab-20c1-4b99-9269-217cb3963abb.png)

**Comment by dariusc93** [comment]
@InfamousVague can you confirm if this is still a issue?

**Comment by dariusc93** [comment]
Shouldve been corrected by now since the issue was related partly to the UI at the time
