### ISSUE TITLE
Sending a message will cause crash

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#160]
**Issue:** If user sends they're friend a message the app will crash. When the log back in the message will appear as sent.

 **How to replicate:**
 1. Add friend 
 2. Send messages 
 
 **Screenshots and recordings:**
 

https://user-images.githubusercontent.com/93608357/199281245-f5ab4955-14cb-436a-a0f0-0c4102741220.mov

 
<img width="998" alt="Screen Shot 2022-11-01 at 12 00 52 PM" src="https://user-images.githubusercontent.com/93608357/199281263-c3466af6-fefe-43ee-be50-1f0c2cced479.png">

**Comment by dariusc93** [comment]
Issue is caused by https://github.com/Satellite-im/Uplink-Desktop/blob/dev/src/components/main/sidebar/chat/mod.rs#L40-L43. Shouldnt be unwrapping like that.
