### ISSUE TITLE
Find Alternative for Box Drawing Unicode Character for Mac/Windows 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#171]
As title says, Box Drawing Unicode Character seems to not work on Windows and Mac OS 

How the reply should look 

![image](https://user-images.githubusercontent.com/93608357/199553129-87562c58-4a20-4ba0-8e01-262d2f614d90.png)

How the reply looks on Mac

![image](https://user-images.githubusercontent.com/93608357/199553369-9728e243-ca0c-400d-9f81-10326ddcbcdd.png)

**Comment by phillsatellite** [comment]
@InfamousVague  Did another Git pull/cargo clean/cargo update and did all new accounts still couldn't get that reply icon to appear correct 

on MacOS

![Image](https://user-images.githubusercontent.com/93608357/199562709-b3bccbc6-6986-4d67-837a-3321c65808ef.png)

**Comment by InfamousVague** [comment]
@sdwoodbury or @calogero93 could you take a look at my code I can't test on Mac ATM

**Comment by phillsatellite** [comment]
@InfamousVague Lucas and I both verified this worked, moving to Closed

**Comment by lgmarchi** [comment]
![image](https://user-images.githubusercontent.com/63157656/201192476-0516998e-0e81-4731-a37f-edfded9acfe8.png)

Working on Mac
