### ISSUE TITLE
Link Previews

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#181]
**Desc**
Links sent should be wrapped in a clickable link.

**Requirements**
- Links should be wrapped in clickable a href.
- Links should show a box below with the first H1 tag, first paragraph tag (max 250 chars) and first image on the page.
- Clicking the box should open the link.

**Resources**
https://crates.io/crates/link-preview

![Image](https://user-images.githubusercontent.com/1770198/199717747-7a8af649-446e-4123-9678-6adb83054166.png)

(don't copy discord's style, this can be used to understand what we're trying to do though. Mockups will be supplied in the future)

**Comment by phillsatellite** [comment]
@InfamousVague I noticed the UI for embedded links looks a little off and if I send a link that is not embedded I cannot click it to go to link. Want me to close and create a new ticket or move this back to To Do?

![Image](https://user-images.githubusercontent.com/93608357/202463424-0e04a2b6-01c9-49cb-969d-ab59bb70ede4.png)
