### ISSUE TITLE
If user selects a profile pic and then changes it again, the new profile pic should update through the rest of the app

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#187]
**Issue:** If user already has a profile picture set, and they change it to a new one it currently will not update throughout the rest of the app and it will not update on any of they're friends sides

**Screen recording and screenshots:**

https://user-images.githubusercontent.com/93608357/199786954-cdddf006-dec0-4529-9670-1162a7299e93.mov

<img width="1939" alt="Screen Shot 2022-11-03 at 1 03 28 PM" src="https://user-images.githubusercontent.com/93608357/199787182-6273608b-1d65-498e-b6c6-f4f05fc818de.png">

**Comment by Jekrimo** [comment]
Update: Currently, updating your own profile pic will update throughout your OWN app, but will not update for your friends unless a reset is made on their part.

**Comment by phillsatellite** [comment]
Another Update: After testing more it looks like now the profile picture will update on both users side but only in chat. In the Sidebar it still will not update
