### ISSUE TITLE
github - automatically delete branch after merge

### ISSUE THREAD

**Issue by josephmcg** [Satellite-im/WarpGUI#220]
someone with admin access will need to do this
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by dariusc93** [comment]
Thought this was already enabled? Can do this here if there is no objections to enabling it 

cc @InfamousVague

**Comment by sdwoodbury** [comment]
I think it's sometimes helpful to keep the branches around for a little while after merging because a subsequent merge could incorrectly handle merge conflicts. in that case it would be helpful to have the old branch for reference.

**Comment by josephmcg** [comment]
There's a grace period of a couple days where you can undo the delete. I find myself spending more time deleting branches than encountering the case above

**Comment by sdwoodbury** [comment]
that's fair. and the branch still exists locally until the dev deletes it, so there's a backup most of the time too.

**Comment by stavares843** [comment]
this is just a setting on admin 😂 we have this enabled on core as well

**Comment by stavares843** [comment]
also if you need the branch we can just restore it, we don't need to keep hoarding branches

**Comment by stavares843** [comment]
darius activated the setting
