### ISSUE TITLE
Account ID is extending past the Sidebar 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#23]
**Issue:** While doing some exploratory testing on WarpGUI I noticed when user opens up the tab, in the bottom left corner the Account ID will be extending out past the sidebar

**Device:** M1 Macbook Pro

**How to replicate:**
1. Open the Profile Tab 

**Screenshot:**
<img width="1288" alt="Screen Shot 2022-09-22 at 6 44 33 PM" src="https://user-images.githubusercontent.com/93608357/191864546-ad03a43f-d65f-4f62-b72b-5beadc477735.png">

**Comment by InfamousVague** [comment]
@Jekrimo is this ready for testing?

**Comment by Jekrimo** [comment]
> 

Yup! It got merged, should be good to go!
