### ISSUE TITLE
When adding a friend to your favorites the User online status does not appear

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#231]
**Issue:** When a user tries to add one of their friends to their Favorites, the friends profile picture will appear but the online status will not appear 

**How to replicate:**
1. Add a friend
2. On top left of screen click the + button or click the heart button in chat
3. Add friend to list 

**Screenshot:**

![Image](https://user-images.githubusercontent.com/93608357/201753576-87c84362-39c1-4b24-82ec-b35a7c3a8d9f.png)

**Comment by phillsatellite** [comment]
Still able to replicate on dev

**Comment by dariusc93** [comment]
Likely due to the status indicator not being tied to favorites.
