### ISSUE TITLE
When replying to a message, the message you are replying to becomes the message you send

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#237]
**issue:** When a user replies to a message, the message being replied to will appear as your own reply 

**How to replicate:**
Reply to a message

**Screenshot:**

![image](https://user-images.githubusercontent.com/93608357/200369125-c5a41501-bd61-4e3c-be74-af3e2c441842.png)

**Comment by sdwoodbury** [comment]
bug introduced here https://github.com/Satellite-im/Uplink-Desktop/pull/184
