### ISSUE TITLE
Update README.md with Building Requirements

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#24]
This should include information for platforms like Windows, Linux and Mac (which for now would be rust, cmake, and protobuf) and how to fetch some dependencies from package managers (eg brew, choco, apt, pacman, pkg, etc).

**Comment by InfamousVague** [comment]
I think we're pretty good with my recent changes to dev, but LMK.

**Comment by InfamousVague** [comment]
I don't know about windows, darius you could add whichever distro you're on and other systems would be great starter issues.
