### ISSUE TITLE
Add Horizontal scroll to the Favorites modal

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#259]
**Issue:** : If user has a lot of friends and adds more than 4 of them to their favorites, the favorites modal will start to look very messy. If we add horizontal scroll that should fix this 

**How to replicate:**
1. Add at least 5 or 6 friends 

*I did this by using `cargo run -- --path /tmp/new1` then new tab and `cargo run -- --path /tmp/new2` etc 

2. Add all of them to your favorites

**Screenshot:**

<img width="328" alt="Screenshot 2022-11-08 at 4 33 31 PM" src="https://user-images.githubusercontent.com/93608357/200680935-ca4387f0-d657-4500-80e9-7e043d52e45f.png">

**Comment by sdwoodbury** [comment]
it needs to scroll horizontally

**Comment by nathan-power** [comment]
Resolved in PR #420
