### ISSUE TITLE
Implement Online Status Indicator

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#26]
This can be done by using `MultiPass::identity_status` which yields `IdentityStatus::Online` or `IdentityStatus::Offline`. 

Note: In the future there will be a way to change it to set the status online, offline, etc.

**Comment by InfamousVague** [comment]
@dariusc93 since we are working with an "always online" model right now without the use of sync nodes, wouldn't the status always be online if we can get ANY info on the user? (maybe not?)

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/37

**Comment by dariusc93** [comment]
Closed in #37
