### ISSUE TITLE
Everything in Profile Modal is shifted to the left 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#278]
**Issue:** When you open Profile, looks like everything except the profile picture got shifted to the left 

**Screenshots:**

<img width="325" alt="Screenshot 2022-11-09 at 6 11 25 PM" src="https://user-images.githubusercontent.com/93608357/200961979-16fd9cea-4edb-4b5c-91bd-d800cc442283.png">

<img width="1713" alt="Screenshot 2022-11-09 at 6 11 07 PM" src="https://user-images.githubusercontent.com/93608357/200962012-7f7a7af2-b9b5-48eb-ae4e-4e9865575692.png">

**Comment by lgmarchi** [comment]
Not using bottom sheet for now to open profile anymore. Closing Issue.
