### ISSUE TITLE
Change error message from "Something went to wrong" to tell the user they already have that friend added 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#279]
Issue: When you try adding a friend that you already have you get an error message that says "something went wrong" we should change it to something like "You are already friends" 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/200979713-73229211-6dd8-4e9b-b635-32a3c10b6158.mov

**Comment by dariusc93** [comment]
in https://github.com/Satellite-im/Uplink/blob/dev/src/components/main/friends/sidebar/mod.rs#L221 (including the other below) one can use `Error::FriendExist` there as an error and display the proper error message for it when a friend already exist
