### ISSUE TITLE
Fix copy into clipboard

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#28]
Under linux (at least under KDE and I3), the crate to copy into the did key into the clipboard does not work. The crate have not been tested separately yet, however this should be investigated to determine if there is an issue with the crate and the way it copies into the clipboard or if there is something blocking X11 under this UI from being able to copy content into the clipboard

**Comment by InfamousVague** [comment]
@dariusc93 if we can do some independent testing to find something that works cross platform I can implement. Do you have a cross platform solution that's confirmed to work?

**Comment by dariusc93** [comment]
I would still have to do testing as it looks like it might be conflict between the DE clipboard manager and this crate since i tried doing it directly with x11 calls and it doesnt set or get anything from the clipboard. I did use arboard too (which does similar things internally) so I would have to investigate into that.

**Comment by InfamousVague** [comment]
Suggest replacing with https://lib.rs/crates/arboard or https://github.com/jetli/yew-hooks/blob/11387ce9a9c8ab27e07b98315309de8c3a55dd7a/crates/yew-hooks/src/hooks/use_clipboard.rs#L126

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/83 @dariusc93 can you confirm this works on your system? If not can you confirm if it works with the menu enabled and the "copy" field available?
