### ISSUE TITLE
List of friends and friends request changes each time user enters friends page

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#281]
**Issue:** If the user leaves the friends page then comes back to it the order in which the friends are displayed will change each time

**How to replicate:**
1. Add some friends 
2. Leave friends page 
3. Go back to friends page

**Screen recording:**

https://user-images.githubusercontent.com/93608357/200980333-cfb20f1d-e2d6-44fe-92b8-bc266f882a26.mov

**Comment by dariusc93** [comment]
This was fixed in #312
