### ISSUE TITLE
User gets an error if profile picture height is too big 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#283]
**Issue:** If the user sets their profile pic and the picture they choose is too big height wise, they will can an error in terminal and when they send a friend request their profile picture will not appear on the friends side 

(I was able to replicate this by selecting a photo from my iOS device) 

**Screen recording / Screenshots:**

https://user-images.githubusercontent.com/93608357/201145563-569ce57c-6fac-4537-96a8-4573a6d2569b.mov

<img width="981" alt="Screenshot 2022-11-10 at 10 59 53 AM" src="https://user-images.githubusercontent.com/93608357/201146161-64736d59-4f62-4d3a-a695-267d9782f5aa.png">

**Comment by dariusc93** [comment]
I already see the issue on why that it shows the image on the profile while giving the error so ill correct that here shortly, but generally there is a size limit for photos and banners which is set to 2MB for right now.
