### ISSUE TITLE
If user has a lot of friends/chats UI will start to take a while to load

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#296]
**Isseu:** When a user starts to gather a lot of friends/chats, when they switch to pages that have to upload in real time like the messages page or friends page it be will noticeably slower than the Settings page and Files. The more messages there are in the chats and profile pictures to load the slower it will become

**Screen recording:**

https://user-images.githubusercontent.com/93608357/201446218-c1c6c80f-1511-4bee-b7cb-4eb324c587ce.mov

https://user-images.githubusercontent.com/93608357/201446221-519b509e-4897-47a1-b06e-cc8eaa6f286e.mov

**Comment by dariusc93** [comment]
@phillsatellite could you try again with the latest dev. @sdwoodbury did do a PR yesterday that was merged in.

**Comment by dariusc93** [comment]
@phillsatellite can you confirm if this is still a issue?
