### ISSUE TITLE
After sending a friend request, DID key should clear out of textbox

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#302]
**Issue:** When the user is adding a friend and they send the request, the did key that they had pasted in the textbox should clear out 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/201739045-5ec009a8-250a-485d-a600-9571c5efb8fb.mov

**Comment by dariusc93** [comment]
I thought it did clear out after sending the request. Probably forgotten to be placed in during the change, but should be simple to do to.
