### ISSUE TITLE
Clicking a notification should automatically open the App 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#303]
Task: If you get a notification and you click it, the app should automatically open up and go to whatever page is related to the notification (Like if you click a friend request notification, it should open up and go straight to the friend request etc)

**Screen recording:**

https://user-images.githubusercontent.com/93608357/201981960-dbf65bad-015d-4196-a29f-bb341ce4dc19.mov

**Comment by drepram** [comment]
For this, we would need a custom handler action. Aside from that, one thing how we can improve the notification is to append `.appname` to the Notification constructor, this will set the icon for the notifications. 

I will look more into this tomorrow!
