### ISSUE TITLE
Drag and dropping a file into chat will cause the typing indicator to freeze

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#304]
**issue:** If user drag and drops a file into chat, the typing indicator will freeze up 
**Screen recording:**

https://user-images.githubusercontent.com/93608357/205934552-c8d54426-2fe1-40b2-af97-c472f0ac64b5.mov

**Comment by InfamousVague** [comment]
Dioxus has information on handling the dragging and dropping of files. My suggested fix for now is to handle the drag and drop event globally (just ignore the event) and add support back in on supported pages later (like in a chat, or on the files page)

**Comment by phillsatellite** [comment]
I retested this today and behavior is a little different now, it will no longer open up the file but the typing indicator will freeze as soon as you drop the file into chat. Updating ticket accordingly 

https://user-images.githubusercontent.com/93608357/205934552-c8d54426-2fe1-40b2-af97-c472f0ac64b5.mov
