### ISSUE TITLE
Unknown chat conversation shown on friends section

### ISSUE THREAD

**Issue by hyj1204** [Satellite-im/WarpGUI#306]
There is an unknown chat conversation shown on the first page of friends. It looks like a loading effect and sometimes changes its location in the list.

https://user-images.githubusercontent.com/14248245/201954977-d05cfc4d-22f9-4028-8255-0b77827c36a8.mov

**Comment by dariusc93** [comment]
Already believe I know what this is about, however what could be done to test to be sure is have the other client reload their client or perform an update like changing username, updating status, etc. If that clears up then I already know what this might be about and been fixed (just not pushed up yet). if not then might be related to something else. Havent reviewed the changes made to split this all up so i might do that sometime today, however if they are already on the friends list, i would suggest having the chat button available and possibly render the did key in its place until the identity is received (so they arent blocked from chatting).

**Comment by phillsatellite** [comment]
@hyj1204 are you able to replicate this still? I've been attempting this morning but haven't been able to 💥
