### ISSUE TITLE
Missing change username feature and status message

### ISSUE THREAD

**Issue by hyj1204** [Satellite-im/WarpGUI#307]
Username is missing in the profile page(setting section) and I am not sure if status message has been changed successfully.

https://user-images.githubusercontent.com/14248245/201982630-5e5a2f07-297a-48ac-8c33-d89123d7d6ce.mov

**Comment by phillsatellite** [comment]
Found this little UI issue when using a narrow browser window, showed Yijing and we thought it was best to add into this issue 👍 

https://user-images.githubusercontent.com/93608357/201991436-e3a452c9-9015-43e8-896e-0ed332382806.mov

**Comment by dariusc93** [comment]
This is pretty easy. Similar to how one would change/update their profile banner or picture they would use the same function but with the `IdentityUpdate::set_status_message` for updating the status, `IdentityUpdate::set_username`  for username.
