### ISSUE TITLE
Textbox in chat lacks padding when user clicks into it

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#31]
**Device:** Desktop Macbook Pro M1

**issue:** When a user is in chat and clicks into the textbox, the blue highlight around the textbox will be touching the Upload file button 

**How to replicate:**
1. Start a chat 
2. Click into the textbox 

**Screenshot:**
![image](https://user-images.githubusercontent.com/93608357/192308867-5f9b1660-1cbc-43bd-888e-7affd9eecb50.png)

**Comment by InfamousVague** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1770198/192348410-196ccb99-1d3d-4dbf-a624-552b110d22fb.png">
@phillsatellite unable to repro on my machine, are you on the latest version of dev, or main?

**Comment by phillsatellite** [comment]
@InfamousVague I can move this to done. This morning was having this issue but checked again after pulling the latest changes and can no longer replicate on my side 👍
