### ISSUE TITLE
Embedded link preview extends outside of reply modal 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#318]
**Issue:** Like title says if you reply to a message with an embedded link, the preview for it will extend outside of the reply modal borders

**Screenshot:**

<img width="581" alt="Screenshot 2022-11-17 at 9 10 04 AM" src="https://user-images.githubusercontent.com/93608357/202468866-927548fe-3fe3-43df-9a33-69c2036c2608.png">

**Comment by jasonwoodland** [comment]
@phillsatellite did you paste an `<iframe>` or just a url for this to occur?

**Comment by phillsatellite** [comment]
@jasonwoodland I pasted the <iframe>
