### ISSUE TITLE
Investigate if we can disable force touch events in app for now. (Grey box appears when user click+holds a message)

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#33]
**Edit:**

> Whoever works on this issue, the goal should be to disable force touch events on WarpGUI.

---

**Device:** Macbook Pro M1

**Issue:** When a user clicks and holds a word within a message in chat, a grey box will appear. (this might just be a MacOS thing?)

**How to replicate:**
1. Send messages in chat 
2. Click + Hold one of the words within the message

**Screen recording:**

https://user-images.githubusercontent.com/93608357/192340356-b26254b4-f359-45a3-9954-a06610aae0c0.mov

**Comment by InfamousVague** [comment]
@phillsatellite do you have a normal mouse to test this with? I suspect this is an apple dictionary thing, it if is, I don't think it will show up on non "force touch" devices, so can you try this with a magic mouse or a standard mouse?

**Comment by phillsatellite** [comment]
> @phillsatellite do you have a normal mouse to test this with? I suspect this is an apple dictionary thing, it if is, I don't think it will show up on non "force touch" devices, so can you try this with a magic mouse or a standard mouse?

will do! 👍

**Comment by phillsatellite** [comment]
> @phillsatellite do you have a normal mouse to test this with? I suspect this is an apple dictionary thing, it if is, I don't think it will show up on non "force touch" devices, so can you try this with a magic mouse or a standard mouse?

Verified that I can only replicate this if I use the trackpad on my Macbook and not if I use the magic mouse

**Comment by InfamousVague** [comment]
Interesting, so it must be something canceling out apple's force touch overlay. Maybe this is an issue with rendering since when you click a message it's supposed to open it up. I suggest we just investigate if there is a way to disable force touch for the app as I can't really see any useful application for it early on.

**Comment by InfamousVague** [comment]
Whoever works on this issue, the goal should be to disable force touch events on WarpGUI.

**Comment by InfamousVague** [comment]
Closing this issue, we should not mark it as done but in an effort to keep the backlog clean, for issues that we do not plan to fix in the current or next milestone I'll close them so we can sort issues easier but still have the ability to search for this issue in the future.
