### ISSUE TITLE
Add pop out animation for slide up modals.

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#34]
**Note:** This issue should be solved using largely CSS. It is okay if we need to add an additional class, however we probably already have enough.

Currently when you click the fullscreen button on the profile picture popup it just appears we should instead modify it so that it has a nice css animation. We can look at something like the macos animation when we minimize or open a window to and from the dock for inspiration. Of course we don't want to copy this but we should have something nicer than it just appearing probably.

**Comment by jamesBaxtuh** [comment]
Hey @InfamousVague, I'd like to have this issue assigned to me.

**Comment by lgmarchi** [comment]
For now, we decided to not use slide up modals. Closing issue for now.
