### ISSUE TITLE
Fix double arrows on dropdown on audio settings

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/WarpGUI#358]
STR:
- go to any chat
- go to audio settings
- double arrows appear

<img width="949" alt="Captura de ecrã 2022-11-20, às 19 16 31" src="https://user-images.githubusercontent.com/29093946/202921401-9ff95a1d-98a8-4793-8deb-3b944f6beea1.png">

macOS

**Comment by nathan-power** [comment]
Hi Sara 👋
The problem seems to be fixed, can you confirm?

<img width="778" alt="スクリーンショット 2022-12-05 14 05 37" src="https://user-images.githubusercontent.com/40599535/205540677-bdd2ccf1-3f08-4a7a-848f-22702531d7c1.png">

**Comment by stavares843** [comment]
🎉
