### ISSUE TITLE
Audio settings can't be dismissed if text message is multi line

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/WarpGUI#359]
STR:
- go to chat
- open audio settings
- add various lines to chat text message
- audio settings icon closes and cant be dismissed

https://user-images.githubusercontent.com/29093946/202921541-0166dbd3-b422-4a8e-b0e4-2e13c74a9c84.mov

macOS

**Comment by nathan-power** [comment]
Hey Sara,
Seems like this one may already be fixed as well

**Comment by stavares843** [comment]
🎉
