### ISSUE TITLE
Issue in extensions/cargo.toml

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/WarpGUI#361]
![image](https://user-images.githubusercontent.com/2993032/202935126-d80365c0-6529-4683-bfe0-0bdf569c8572.png)

something with this commit: https://github.com/Satellite-im/Uplink/commit/12fc906957c023ae4520442774a7278a55793190

**Comment by WanderingHogan** [comment]
no one else has an issue like this, closing because it must be an error just with my local

**Comment by dariusc93** [comment]
Related to #366
