### ISSUE TITLE
Perform background task to update username and profile picture

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#368]
When a username, profile picture, etc., updates, the UI does not update unless one switch from one tab and go back to the other to see it get rendered in. Noticed this while testing a PR. I would suggest having a background task to compare and update states containing the username, picture, etc. This would reduce the need of manually updating the UI by switching tabs.

**Comment by dariusc93** [comment]
To make this easier for some components, passing `UseState` reference across components would make it easier to update. Using PFP as an example, 

```rust
#[derive(Props, PartialEq)]
pub struct Props<'a> {
    #[props(!optional)]
    src: &'a UseState<Option<String>>,
    size: Size, // todo: why is this unused?
}

#[allow(non_snake_case)]
pub fn PFP<'a>(cx: Scope<'a, Props>) -> Element<'a> {
    let style = match cx.props.src.get() {
        Some(img) => format!("background-image: url({});", img),
        None => "".into(),
    };

    cx.render(rsx! {
        div {
            class: "pfp",
            style: "{style}"
        }
    })
}

```

And whenever we update a state that passes `UseState` reference, PFP would change as well and updating the component that uses PFP.

Another suggestion could be to pass `DID` and `Account` and perform the update task in those components directly based on what is being updated, though i think the former would be better. 

cc @sdwoodbury

**Comment by hyj1204** [comment]
Add more info related to this issue
https://github.com/Satellite-im/Uplink/pull/385#issuecomment-1324375139
