### ISSUE TITLE
File: File UI Updates

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#370]
**Issue:** In files page, adjust the text in the usage bar so it's on top and visible as the user changes the screen size. Also - when in mobile view, show the usage bar at the top of the panel that is shown.

**Other Changes/Updates:**
It was specifically mentioned that in mobile view, we want to see the larger/right panel that shows the folder icons (with a list view coming later) and not the tree menu from the left side bar. I am not sure if this has changed @InfamousVague? It looks like it has been refactored to show the sidebar on collapse, and remove the footer show logic and the folder/file add and usage bars. Do you want it the current way, or the way it was before?

**Screenshot:**
<img width="700" alt="Screen Shot 2022-11-29 at 9 23 55 AM" src="https://user-images.githubusercontent.com/2993032/204592293-a0bcb9e6-fb99-438f-a964-aee5e2bea297.png">

<img width="444" alt="Screen Shot 2022-11-29 at 9 58 34 AM" src="https://user-images.githubusercontent.com/2993032/204593616-1fff4f0b-cf87-4af2-a588-e8fe6afce202.png">

**Comment by WanderingHogan** [comment]
@nathan-power You mentioned you are actively fixing the top bar, can you find out about the actual mobile view and adjust this ticket to reflect that?
