### ISSUE TITLE
Create Mock-Up of Spotify Player Extension

### ISSUE THREAD

**Issue by XileHorizon** [Satellite-im/WarpGUI#373]
__Overview__: Create a mock-up for a plugin to control a connected Spotify account on Uplink Desktop.

__Resources__:  https://betterdiscord.app/plugin/SpotifyControls

![Image](https://user-images.githubusercontent.com/33043119/203409434-3b6fc7e2-54f9-46b4-8f66-179c911b4b55.png)

![Image](https://user-images.githubusercontent.com/33043119/203409322-a49e5da9-36e8-44ba-88e7-b33d8e183cf4.png)

**Comment by XileHorizon** [comment]
Added "Loop" and "Shuffle" Icons

![Image](https://user-images.githubusercontent.com/33043119/205987710-39b25c88-9cb2-4368-87cd-5869bc724109.png)

**Comment by imeatincookies** [comment]
<img width="986" alt="Screen Shot 2022-12-06 at 12 45 08 PM" src="https://user-images.githubusercontent.com/118937106/206019170-7cd11628-17de-4fca-8314-fee2a3f5a56e.png">
