### ISSUE TITLE
Implement automatic loading of UI extensions (load extension)

### ISSUE THREAD

**Issue by calogero93** [Satellite-im/WarpGUI#38]
Should be able to drag and drop an extension into the extensions folder
Finding a way to upload the extension inside the application.

Possible Solution:
Use of the dynamic libraries. 
Upload them and use their function to return the extension to render inside the app
Load dynamic library form setting page upload and store it inside `.warp` directory and adding the path inside `Config.toml`

**Comment by dariusc93** [comment]
Meant to respond to this a couple of days ago but it was talked about utilizing dynamic libraries to handle this. While that would be a option (which you can load/unload at runtime), you should keep in mind that if you use dynamic libraries you would generally need one for each platform (eg linux, windows, mac, etc), which can make things complex if one is using a platform specific api. Its really hard to tell what is the goal of this ticket, however I would probably suggest using wasm/wasi as libraries instead (eg you can use [wasmtime](https://github.com/bytecodealliance/wasmtime)  to load wasm modules at runtime and execute functions there to return various of data).  

I would like to request some additional information regarding this issue so I can provide better advice and make suggestions accordingly.

**Comment by calogero93** [comment]
Thanks @dariusc93  I'll have a look at that libraries too.
To reply at your question, the goal of this ticket is to have an extension that can be loaded and make it usable inside the application at runtime, for example I would have an extension that add an emoji, in this case I have to found a way to load that extension inside application at runtime and find that emoji on the keyboard or wherever you want.
But as a first step the goal is to load the extension correctly

**Comment by dariusc93** [comment]
It sounds like something that can be a data pack? If its something like emojis, images, etc., stuff like that might be doable without a dynamic library but maybe have some type of toml (or even yaml, josn, etc) config with specific fields to point to the assets and bundle that config along with the assets into a zip (or tar, etc) that can be loaded at runtime from that directly and you read from that specific file that points to the assets. Of course, you could still use a dynamic library (or even a wasm module since that might be easier and safer to do) but I guess more clarity would be needed if that route will be done too

**Comment by calogero93** [comment]
Not properly, from my understanding an extension can add also other features, like a button that can do something.
But maybe @InfamousVague has some other suggestion. Waiting for him.

**Comment by calogero93** [comment]
Implemented solution:

Build a dynamic library for each extension
put the extension inside the extension folder (`.warp/extension`)
By means of `get_extensions` function inside `extensions` module reads and extracts the `ExtensionManager` that contains `info` and pointer to `render` function for each extension
By means of `get_render` function inside `extensions` module we get a vector of all of the rendering of the extensions for a given widget and put the on the Widget's `render` function
