### ISSUE TITLE
Persist when a user accepts the 'pre release software' notification

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/WarpGUI#383]
Check out how global state works in src/state/mod.rs, persist that check

**Comment by WanderingHogan** [comment]
<img width="479" alt="Screen Shot 2022-11-22 at 3 04 15 PM" src="https://user-images.githubusercontent.com/2993032/203430721-56f9d018-09cf-4f9c-8ab8-b39f9d78798e.png">

**Comment by dariusc93** [comment]
Thought it got saved into the persistent state but simple to do
