### ISSUE TITLE
Message Replies

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#39]

**Comment by dariusc93** [comment]
Just as a note here to make sure things are clear:

When replying to a message you want to use `Message::id` when supplying it to `RayGun::reply`. On top of that, if the message that is being replying to is going to be rendered you would want to use `RayGun::get_message` to get the single message

Just as an example code of listing the messages in all conversations, including replies

```rust
let conversations = raygun.list_conversations().await?;
for conversation in conversations {
  let messages = raygun.get_messages(conversation.id(), Default::default()).await?;
  for message in messages {
       if let Some(replied_id) = message.replied() {
          let message = raygun.get_message(conversation.id(), replied_id).await?;
          println!(">> {}", message.value().join("\n"));
       }
       println!("> {}", message.value().join("\n"));
  }
}
```` 

Note: You would be using `use_future` (unless the specific function where the vnode is at is async) so make sure to restart it as well.

**Comment by InfamousVague** [comment]
Awaiting https://github.com/Satellite-im/Uplink-Native-/issues/36

**Comment by phillsatellite** [comment]
Holding off a couple mins on moving to done. @tooshel had said that replies weren't working on Windows. Getting Uplink setup on my Windows so I can verify as well

**Comment by tooshel** [comment]
@phillsatellite FYI, we figured out that the problem was that a button was not connected and if I pressed "enter" they worked fine on Windows.

**Comment by phillsatellite** [comment]
@tooshel Awesome news thanks for letting me know!

**Comment by phillsatellite** [comment]
@InfamousVague I'm thinking this ticket just didn't get linked to PR but replies are working on dev now, cool if I close this ticket?

**Comment by tooshel** [comment]
@phillsatellite Yeah, I think we can close it! We have "project_status" and "issue status" and the only thing keeping them in sync is my and you! Closing this now.
![image](https://user-images.githubusercontent.com/223338/201383392-18cb4128-3ee9-4abd-9665-46717ae6ef6a.png)
