### ISSUE TITLE
Context menu is rendering off screen if user right clicks near edges of the window 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#390]
**Issue:** Like title says, if the user right+clicks near the bottom/top edge of the window some and/or all of the context menu will be rendered off screen. This is the same for is User has they're window adjusted to be narrow and they right+click the right side of the window, only half the context menu is rendered.

**Screen recording:**

https://user-images.githubusercontent.com/93608357/203457557-faeb916c-1b3d-4b66-b735-d2735c6e8169.mov

https://user-images.githubusercontent.com/93608357/203458056-5dfd677e-d18f-41e1-8cfd-da1608e9ea37.mov

**Comment by josephmcg** [comment]
https://github.com/Satellite-im/Uplink/pull/401
