### ISSUE TITLE
Update username validation rules in creating account

### ISSUE THREAD

**Issue by hyj1204** [Satellite-im/WarpGUI#397]
Apply the following rules in username

- Length between 4-32 characters.
- No space in the beginning and end(Trimed). Allow space in the middle of text.
- @ is not allowed.
- Only allow alphabetic, digits and punctuation(No emoji).

![image](https://user-images.githubusercontent.com/14248245/203595191-f9e31262-4d21-4ef7-9271-771ea2856bc0.png)

**Comment by dariusc93** [comment]
The rules should also follow when updating the username too
