### ISSUE TITLE
macos popup every time i receive a friend request

### ISSUE THREAD

**Issue by josephmcg** [Satellite-im/WarpGUI#421]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/33670767/203913769-ccc67121-2c1b-4942-ae0f-7f3a3d241634.png">

**Comment by dariusc93** [comment]
Does that popup each time you receive a request?

**Comment by InfamousVague** [comment]
It's because the app is unsigned, not sure we can get past this for a bit, if you pick anything from that list it'll go away.

**Comment by drepram** [comment]
> It's because the app is unsigned, not sure we can get past this for a bit, if you pick anything from that list it'll go away.

Yep, precisely what Matt said.

**Comment by drepram** [comment]
> Does that popup each time you receive a request?

I don't think so. This is only when you first start your instance and haven't received your first notification. If you click `cancel` on it, it will default to the Finder logo and get notifications this way:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/34530026/204340141-b3194b1a-a1ac-4eb0-bb96-4cc3eae4bd8e.png">

**Comment by WanderingHogan** [comment]
We will be notarizing/code signing soon on pul requests with this issue: https://github.com/Satellite-im/Uplink/issues/333 which can be adapted to releases

**Comment by josephmcg** [comment]
ok seems like signing will resolve, gonna close
