### ISSUE TITLE
Hitting Enter will start a new line of text instead of send message

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#444]
**issue:** This problem is not always able to be replicated, sometimes it seems like after having the app open for a while if you type up a message and hit enter it will start a new line of text instead of sending message. I noticed when this happens the rest of the app will be frozen User can't navigate to a different page.

**Screenshot:**

https://user-images.githubusercontent.com/93608357/204361239-7b7af3d5-1b12-436e-be1a-43f5d22a1ad6.mov

**Comment by dariusc93** [comment]
Is this an issue observed on latest dev? Was talking to Joe last night about this issue which seemed to not happen on release (though ive seen it happened once on release last night during testing) but i've also seen it not happen on a recent PR (under debug and release) but seemed to have happened sometime after the typing indication was implemented. 

cc @sdwoodbury

**Comment by phillsatellite** [comment]
> Is this an issue observed on latest dev? Was talking to Joe last night about this issue which seemed to not happen on release (though ive seen it happened once on release last night during testing) but i've also seen it not happen on a recent PR (under debug and release) but seemed to have happened sometime after the typing indication was implemented.
> 
> cc @sdwoodbury

Yeah Sara and I both experienced this issue on dev branch

**Comment by dariusc93** [comment]
> Yeah Sara and I both experienced this issue on dev branch

Could you try it while under the release? Is it at random in mid conversation or is it consistent after restarting client?

**Comment by InfamousVague** [comment]
I think this issue is caused by the input being cleared after the message is sent on warp, not before; instead what we need to do is send the message with some visual indication it's still going out to the user; instead of just waiting for it to be successful before we send the message.

**Comment by phillsatellite** [comment]
I retested this more and found how to replicate each time, if you type a message and hit _Shift_ + _Enter_ rapidly and then continue to keep hitting the _Enter_ key but release the _Shift_ then bug will appear. 

When I first tested this in release I was able to still replicate but this time I was only able to replicate this while not in release.

**Comment by phillsatellite** [comment]
@stavares843 and I havent been able to replicate while testing throughout the day going to close for now, will re open if I can get bug to appear
