### ISSUE TITLE
If user rapid clicks send when sending a file, multiple files will be sent

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#447]
**Issue:** Like title says, if you select a file to upload and then rapid click the send button, it will send multiple files in chat

**Screen recording:**

https://user-images.githubusercontent.com/93608357/204388781-2fb4448d-4b6a-4f25-9e0f-2e6c4aa1eec6.mov

**Comment by jasonwoodland** [comment]
Unable to reproduce on b716287

**Comment by dariusc93** [comment]
@phillsatellite can you confirm?

**Comment by phillsatellite** [comment]
Yup, when retested on dev its still an issue 


https://user-images.githubusercontent.com/93608357/206582589-152468f3-af70-4755-9354-a3831fc175e4.mov
