### ISSUE TITLE
Investigate Native Mobile Support

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/WarpGUI#457]
https://github.com/DioxusLabs/dioxus/issues/613

Review that, and the dioxus documentation, and see what we need to add to the Cargo.toml and the makefile, and try to generate a mobile app (android or ios). 

If it cant be done, write here what your findings are, shortcomings, issues, etc so we can figure out what to do.

**Comment by WanderingHogan** [comment]
whoever works this one, I will probably work with you

**Comment by dariusc93** [comment]
Make sure to install cargo-mobile, cargo-ndk, android-ndk (latest LTS should do), and xcode (for mac/ios) but in any attempts of getting this working with mobile make sure to CC me in. Android should work just fine (though a little bit of tuning may be needed) but havent tested with ios so ping me when attempting or having issues with ios.

Note for both Android and iOS
* Lower connection limits should be set (this can be done in mp-ipfs config although still need testing overall - see https://github.com/Satellite-im/Warp/issues/68).

* Permissions would have to be take into considerations for filesystem, networking, etc. 

* Not all crates are compatible with android and ios. Warp and its dependencies are so far compatible (pending testing for ios but should be), however i cannot say the same about the dependencies for uplink.

Notes for IOS:

* Extensions system will not work as apple policy forbids shared libraries. They would have to be statically link or omitted at compiletime when targetting ios

* Apple is pretty strict and so keep in mind when it comes to targeting their platform. 
  
Notes for Android:

* Would have to confirm but I believe google made changes to where libraries cannot be loaded externally from the apk but would require to be loaded only from within the apk.

* Extensions would have to be compatible with ndk (see https://github.com/Satellite-im/Warp/blob/8f2bfdf5cf825450bb7d55a6aa6854d66fd61b20/.github/workflows/warp_dart_update.yml#L100-L113)

**Comment by josephmcg** [comment]
putting this on hold until after the large update in approximately 1 month.

Thanks for all the info, Darius!
