### ISSUE TITLE
i18n and fluent - internationalization and localization in Uplink

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/WarpGUI#462]
https://projectfluent.org/ is the project Matt indicated he wanted to use, not sure what else we will need to use with it.

@josephmcg found https://crates.io/crates/cargo-i18n which might make it easier to use Fluent.

Here is ours, so far:

```
global = Application
    .location = Location
    .unknown = Unknown
    .badge = Badge
    .account = Account
    .username = Username
    .status = Status
    .save = Save
    .edit = Edit
    .create = Create
    .message = Message

account = Account
    .status = { global.status }
        .placeholder = Some { global.status } {global.message}...
        .save = { global.save } { global.status }
    .edit = { global.edit } {account}

prelude = Prelude
    .register = Register
        .choose_username = Choose { global.username }
        .create = {global.create} { global.account }

choose-username = Choose a { global.username }
```
in src/language/en_US.ftl

Steps: 
- Figure out how to use fluent and what other libraries we will need
- build the fluent rules library/configure it
- Start adding a translations file that can use it and retrofit a few components?

Does that sound reasonable? Def feel free to break this into a lot more tickets because it's a can of worms

**Comment by josephmcg** [comment]
pr above has reasons for closing
