### ISSUE TITLE
remove html labels unless tied to an input

### ISSUE THREAD

**Issue by josephmcg** [Satellite-im/WarpGUI#483]
semantically, labels are best suited for inputs. There are many labels throughout the app which should probably be divs or headings with a css class instead.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by InfamousVague** [comment]
We can probably just go for a summary tag like github does.
<img width="595" alt="image" src="https://user-images.githubusercontent.com/1770198/205139956-d1146dfd-4e82-4e8b-9001-b9df5bf5be6b.png">


Also worth noting github also "misuses" them 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1770198/205140184-b12cf620-7900-406d-b47f-5700b0eedab6.png">

**Comment by josephmcg** [comment]
oh nice I didn't know about summary.

Github is appropriately using label in that example. It's inside of a form, referencing a specific image upload input
