### ISSUE TITLE
Profile - Save button for Username and Status only shows "S.." 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#487]
**Issue:** In the Profile page in Settings, the save button for Username and Status only shows "S..." instead of "Save" This bug happens in fullscreen and with smaller browser window 

**Screenshot:**
<img width="639" alt="Screenshot 2022-12-01 at 9 11 13 AM" src="https://user-images.githubusercontent.com/93608357/205074784-da059e4e-61d6-4d48-8d43-3d9533105b4e.png">

**Comment by InfamousVague** [comment]
this can probably be fixed by setting the button's min width to `min-width: fit-content`. Not sure if there is a better CSS fix though.
