### ISSUE TITLE
fix rustfmt warning

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/WarpGUI#492]
<img width="770" alt="Captura de ecrã 2022-12-01, às 18 46 37" src="https://user-images.githubusercontent.com/29093946/205135133-aee7b861-5c22-48f4-aee3-746587f882e9.png">

**Comment by drepram** [comment]
How to reproduce? I pulled the latest change
<img width="752" alt="image" src="https://user-images.githubusercontent.com/34530026/205228540-27ba4bac-d470-4b60-84b3-7be08a2ebd8e.png">

**Comment by stavares843** [comment]
seems it got fixed meanwhile 🔨
