### ISSUE TITLE
fix clippy warnings

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/WarpGUI#493]
<img width="1007" alt="Captura de ecrã 2022-12-01, às 18 47 39" src="https://user-images.githubusercontent.com/29093946/205135202-3035a93b-9ac0-44a7-9346-b7fdfdea2689.png">

**Comment by drepram** [comment]
How to reproduce? I pulled the latest change
<img width="752" alt="image" src="https://user-images.githubusercontent.com/34530026/205228540-27ba4bac-d470-4b60-84b3-7be08a2ebd8e.png">

**Comment by stavares843** [comment]
seems it got fixed meanwhile 🔨
