### ISSUE TITLE
Pass Multipass and Raygun as Prop

### ISSUE THREAD

**Issue by dariusc93** [Satellite-im/WarpGUI#5]
Currently multipass and raygun are stored as static variables, however this creates a bit of redundancy due to having to read 2 reference counters (one being Rc within AtomRef, and other being Arc, which warp utilizes), while also having to unwrap a `Option`. While this shouldnt be a problem since unwrapping and reading is done after account loading (or creation), it can lead to some confusion and possible issues down the road. Passing them as a properties would allow initialization a head of time and allow the code to look clean and allow expected behaviour down the road.

**Comment by InfamousVague** [comment]
@dariusc93 I think this is fixed with the latest merge of your `TEST` branch, is there more to do here or can we safely close this?

**Comment by dariusc93** [comment]
Would probably want to remove the branch from `Cargo.toml` and investigate the username issue I mentioned in the draft pr but besides that it should be fine

**Comment by dariusc93** [comment]
Resolved in recent merge in dev
