### ISSUE TITLE
Sudden issues with sending and receiving friend requests 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#533]
**Issue:** Like title says, today we've been running into some issues sending and receiving friend request. Usually when you send the request, the outgoing request will just appear as the grey loading bar. When Matt tried to add me the Search Friend textbox turned grey and it wouldn't appear under outgoing request 

**Screenshot:**
![image](https://user-images.githubusercontent.com/93608357/206064355-44e5f9d0-4e9e-49fb-8fd4-43d3b6763669.png)

**Comment by dariusc93** [comment]
i have been using this just fine. Can you confirm if its specifically on mac or does it happen on other platforms like windows and linux?
