### ISSUE TITLE
typing indicator broken

### ISSUE THREAD

**Issue by sdwoodbury** [Satellite-im/WarpGUI#547]
as of commit ebbc0d1210c34b16aeacb3c0de629571b1d3231a in dev, the typing indicator doesn't work. I believe the reason is that in `lib.rs` line 53, `send_typing` defaults to false. 

I believe this field was added so an extension could be used to turn off the typing indicator. this probably just needs to be overridden when `PersistedState` is created. 

Also, `iuikit` can be removed since it only contains a `TextArea` which was copied to `components/reusable`.

**Comment by dariusc93** [comment]
`send_typing` should default to true at https://github.com/Satellite-im/Uplink/blob/dev/src/state/src/lib.rs#L113 unless its still false else where in some way

**Comment by sdwoodbury** [comment]
> `send_typing` should default to true at https://github.com/Satellite-im/Uplink/blob/dev/src/state/src/lib.rs#L113 unless its still false else where in some way

I had an old version of `PersistedState`
