### ISSUE TITLE
Create Pin - User is able to use "space" as chars for a Pin

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#55]
1. Create a Pin by just pressing 4 times spacebar
2. Press Enter and pin is accepted

**Comment by InfamousVague** [comment]
Trying to decide if we should fix this or not, in theory the space character should be no more or less secure than an alphanumeric, it may even be more secure because people don't expect  pins in passwords... what do you think @dariusc93

**Comment by dariusc93** [comment]
If you are accepting alphanumeric characters then a space is fine as long as its not all spaces. If it will be numeric then spaces should be ignored. If you ask me, we should ignore spaces here unless we open a option to accept alphabetic or alphanumeric in which case there should be a option to flip between either the numeric pin format or entering a phrase.

**Comment by InfamousVague** [comment]
We do have the option for alphanumeric the pin is really just any combination of key-presses that take up only one character.

Closing this issue, we should not mark it as done but in an effort to keep the backlog clean, for issues that we do not plan to fix in the current or next milestone I'll close them so we can sort issues easier but still have the ability to search for this issue in the future.
