### ISSUE TITLE
Create Account - Username input does not respond quick when typing fast

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#59]
This is the issue that was commented on discord. I am seeing this one too

1. Create Pin and press enter
2. Type fast on username input any text
3. Chars displayed in input are not corresponding to what user is typing

**Comment by InfamousVague** [comment]
Should be resolved on latest, be sure to `cargo clean` and `cargo update`

**Comment by tooshel** [comment]
@luisecm is this fixed now?

**Comment by luisecm** [comment]
@tooshel @InfamousVague I tried with the latest dev and works correctly. Closting it now.
