### ISSUE TITLE
Create Account - Username can be empty after just pressing enter

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#60]
1. Enter a valid pin
2. In create account screen, put the cursor on user input but don't add any chars
3. Press enter
4. User can pass to the next screen even when username was empty

**Comment by dariusc93** [comment]
Will test this and might add a fix on the UI side, however I did add a precheck on warp side (mostly to fix a different thing) so this *should* error if the username is empty (but would generate a username automatically if `None` is supplied to the username)
