### ISSUE TITLE
Unlock Pin - After entering a wrong PIN the "X" button does nothing

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#61]
1. Enter a PIN and create an account
2. Close the app
3. Open the app again and enter a wrong pin
4. Press enter and "Invalid or incorrect pin supplied" message is displayed
5. The check button is changed for an "X" (cancel) button, which does nothing.

Note: When I saw this button, I thought it was going to clear out the input

**Comment by InfamousVague** [comment]
Changed to disable the mouse pointer and turn red to make things more clear (in upcoming PR)

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/76
