### ISSUE TITLE
User receives 2 notifications when an incoming friend request comes in 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#610]
**Issue:** When you get a friend request, you will receive 2 notifications for just 1 friend request 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/207401781-d4588b80-2f1f-4fe6-a970-8c149aac90ff.mov

**Comment by dariusc93** [comment]
I noticed this too. It doesnt happen when the other is offline and comes on to receiving the request so i may take a look into that to see if another notification is being outputted when receiving the event.

**Comment by phillsatellite** [comment]
@dariusc93 sweet! Feel free to shoot me a message if you need me to do any testing with it! 👍

**Comment by phillsatellite** [comment]
Haven't been able to replicate so far tonight gonna keep it open and test more tomorrow
