### ISSUE TITLE
Unlock Pin - Invalid pin message is displayed even when pin entered was correct

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#62]
1. Enter a pin and create account (can be a 4 digit pin, example 1234)
2. Close the app
3. Open the app again and enter a wrong pin with 6 chars
4. Press enter to see the invalid or wrong pin message
5. Press backspace 6 times to attempt to delete the pin (dots are not removed)
6. Enter the correct pin (example 1234) and press enter
7. User will continue to see the invalid or wrong pin message even after typing the correct pin

**Comment by InfamousVague** [comment]
I couldn't reproduce this, I may have fixed it by accident I'll put in the PR let me know if this persists on your system.

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/76
