### ISSUE TITLE
Friends - Invalid friend code message is still displayed after clearing the input

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#63]
Probably this is not an issue, but its kinda weird to keep seeing this message after you cleared out the input bar

1. Enter a PIN and create account
2. Go to Friends and attempt to add a friend using an invalid did key
3. "Invalid friend code" message is displayed
4. User clears the add friend input and "Invalid friend code" message is still displayed on screen, until user copy/paste a valid didkey and press enter to add the friend

**Comment by dariusc93** [comment]
This is related to https://github.com/Satellite-im/WarpGUI/blob/dev/src/components/main/friends/mod.rs#L136 and/or https://github.com/Satellite-im/WarpGUI/blob/dev/src/components/main/friends/mod.rs#L172. Could probably add a timeout to clear it or when there is an input event to clear the error.

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/79
