### ISSUE TITLE
Double clicking sidebar highlights entire modal

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#65]
**Device:** MacbookPro M1

**Issue:** If the user double clicks the anywhere in the sidebar the entire sidebar will be highlighted 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/193368232-ddd94352-5684-44bf-8879-c757a6e9a90d.mov

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/81
