### ISSUE TITLE
Friends - Error message for friend request already sent is still displayed after accepting friend request

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#66]
1. Create accounts from User A and User B
2. User A sends a friend request from User B
3. At the same time, User B sends a friend request to User A and message "You've already sent this request" is displayed (issue also reported)
4. User B accepts the incoming request from User A
5. User B can start a conversation with User A now, but the "You've already sent this request" message is still displayed in screen
6. Even if User B goes to "Profile" or start the conversation, if User B goes to "Friends" again, the error message is still displayed in screen

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/82
