### ISSUE TITLE
If user has long username, it will extend past sidebar

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#67]
**Device:** MacbookPro M1

**Issue:** If the user makes they're username extremely long it will extend past the sidebar. Maybe we could add a char limit for username and also profile status as well. 

**How to replicate:**
1. Create an account 
2. Make username extremely long 
3. Notice username extends past sidebar 

**Screenshot:**
![Image](https://user-images.githubusercontent.com/93608357/193369202-ff2790dc-715b-4c00-a289-3a4020b1c05d.png)

**Comment by dariusc93** [comment]
The UI should have a limit for this too (warp does limit how long a username, status, etc., can be) but this is mostly related to the UI.

**Comment by InfamousVague** [comment]
https://github.com/Satellite-im/WarpGUI/pull/78

**Comment by InfamousVague** [comment]
@dariusc93 warp should have a limit as well as people can bypass it and make stupid long names which are excessive.  I propose we impl a hard limit at 26 for now on warp, and the UI.
