### ISSUE TITLE
Messaging - Cannot send message replies

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#69]
1. User A sends a message to User B
2. User B clicks on message received and reply popup is displayed
3. User B types a random text
4. Reply is not sent when entering press button
5. Reply is not sent when clicking on send button

![image](https://user-images.githubusercontent.com/35935591/193370252-0fef8c47-e16c-4edd-852d-1bc4ce69507c.png)

**Comment by dariusc93** [comment]
The replies is just a placeholder for now. #39 would be what implements it when that time comes

**Comment by luisecm** [comment]
@dariusc93 Closing this for now, as per Darius comments
