### ISSUE TITLE
Messaging - Timestamp is not correct for a group of messages

### ISSUE THREAD

**Issue by luisecm** [Satellite-im/WarpGUI#70]
1. User A sends several messages to User B
2. User B replies
3. Conversation continues along both users
4. After some time, the timestamp for the group of messages sent is wrong (in the example states 39 seconds ago, even though there other messages below with more time

![image](https://user-images.githubusercontent.com/35935591/193370496-f60d0359-09e7-4dd3-a7bb-9addd5ccd9d9.png)

Also:

The last message received keeps displaying "now", even after several minutes have passed since it was received

**Comment by dariusc93** [comment]
If you were to switch to another conversation and come back, does it come back correct or updated? That is a strange one honestly

**Comment by InfamousVague** [comment]
IIRC the way it's setup now it just puts the timestamp below the last message sent, it should have the timestamp of the last update for that block of messages. Ideally we should say if a message is over n minutes after the last one then start a new group but I don't think that logic exists right now.

**Comment by phillsatellite** [comment]
@InfamousVague another ticket thats fixed on dev going to close for now
