### ISSUE TITLE
2 Chats from same user will be created if both users start a chat at the same time

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#71]
**Issue:** Matt and I noticed that if you add a friend and you and that friend both start a chat at the same time there will be a duplicate chats with that friend in the sidebar. 

*Sidenote - I noticed that if this happens and I try to enter the duplicated chat my system will crash

**How to replicate:**
1. Add a friend 
2. Once accepted both of you start a chat at the same time 

**Screenshots:**
![Image](https://user-images.githubusercontent.com/93608357/193376362-1a87c0cd-1cb6-4282-92f3-9fa4469e0f65.png)
![Image](https://user-images.githubusercontent.com/93608357/193376368-21cdf9bb-4c11-4aec-bdc9-f656db8aa97b.png)

**Comment by InfamousVague** [comment]
@dariusc93 Hoping you can take this one, I think it's an issue inside warp. Realistically we should not be able to do this but I think there is a networking race condition here so we need some way to deal with conflicts here..

**Comment by InfamousVague** [comment]
Attached is a test account with the bug visible. Pin is `0000`.

[cache.zip](https://github.com/Satellite-im/WarpGUI/files/9690753/cache.zip)

**Comment by phillsatellite** [comment]
Sara and I both couldnt replicate after multiple attempts and then I tried again later and couldn't replicate with Matt either. Going to move this ticket to close cc: @InfamousVague

**Comment by phillsatellite** [comment]
Moved back to ToDo and re opened Darius and I have both replicated this morning

**Comment by InfamousVague** [comment]
@phillsatellite is this still an issue?

**Comment by dariusc93** [comment]
This shouldnt be an issue anymore since Ive change it in warp to prevent this from happening. Also shown phil how to reproduce it prior to the change.

**Comment by phillsatellite** [comment]
@InfamousVague @dariusc93 I haven't been able to replicate yet this morning with my own 2 devices I can test with Sara to verify issue is gone 👍
