### ISSUE TITLE
the y in "No active chats, yet..." appears like its touching the "start one" button

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/WarpGUI#72]
**Issue:** When a user has no friends and the sidebar has the "No active chats, yet..." the bottom of the y looks like it is touching the "start one" button

**Screenshot:**
<img width="231" alt="Screen Shot 2022-09-30 at 10 18 29 PM" src="https://user-images.githubusercontent.com/93608357/193379349-18665256-e5e9-4a6d-9bf8-f60c366d7289.png">

**Comment by lgmarchi** [comment]
Different UI now. Closing Issue. 
![image](https://user-images.githubusercontent.com/63157656/201187534-9febfdc6-5316-428c-9299-2b0d25e4ba4a.png)
