### ISSUE TITLE
Create incoming friend request count indicator in top right of icon in navbar

### ISSUE THREAD

**Issue by InfamousVague** [Satellite-im/WarpGUI#85]
This should match the mockups and display the total count of open friend requests we have. You should talk to @randombytes to chose the best course of action for this (Initally I had designed warp to include hooks for non-resource intensive event subscription, this should ideally be used)

![Image](https://user-images.githubusercontent.com/1770198/193434341-993687ea-6118-4ef4-87e2-a5574f5dbcca.png)

**Comment by InfamousVague** [comment]
Related: https://github.com/Satellite-im/WarpGUI/issues/86

**Comment by dariusc93** [comment]
Resolved in https://github.com/Satellite-im/Uplink-Desktop/pull/103
